#开发环境配置
server:
  port: 8001
#禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
spring:
  thymeleaf:
    cache: false
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: Huang000
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

#常用的日志级别按照从高到低依次为:ERROR、WARN、INFO、DEBUG
logging:
  config: logback.xml
  level:
    com.hzht.course01.dao: trace

#自定义配置，url为前缀
url:
  orderUrl: http://localhost:8005
  userUrl: http://localhost:8006
  shoppingUrl: http://localhost:8007
  corsUrl: "*"

# 数据库地址
datasource:
  url: localhost:3306/test

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.hzht.course01.entity
  configuration:
    map-underscore-to-camel-case: true # 开启按驼峰命名规范映射
  mapper-locations: # mapper 映射文件位置
    - classpath:mapper/*.xml
